### ISSUE TITLE
Compatibility with DietPi

### ISSUE THREAD

**Issue by Ry-Kode** [RaspberryConnect/AutoHotspot-Installer#17]
Hello,

Thanks for your efforts and sharing this great tool!

Can this be used on DietPi running on Raspberry Pi (4B in my case)?

Best,
J.

**Comment by RaspberryConnect** [comment]
Hi J

I have not tested it on DietPi but the main requirement is that the network devices are managed by dhcpcd, the same as PiOS, rather than Network Manager or dhcp etc.
By default the PiOS also doesn't use  Predictable Network Interface Names so wlan0 and eth0 are used in the script, but the device names can be changed in the autohotspot scripts variables.

The installer will check for a Debian or PiOS installation with dhcpcd running before continuing the install. 
If it meets these requirements it may work but I can't guarantee it will.

I would be interested to know either way though.

Regards
Graeme

**Comment by Ry-Kode** [comment]
Hi Graeme,

I ran a test on Dietpi with a Bullseye image. Unfortunately the test was unsuccessful:

```
OS Version 11
Debian OS detected
dhcpcd is not the default DHCP client
This script is intended for the Raspberry Pi OS
and requires dhcpcd to be the default DHCP client

```
I thought Dietpi was using dhcpcd but it looks like this is not (or longer, pretty sure they used to) the case.

Anyway, thanks again for your great work. Looking forward to seeing the Bookworm-version!

BR,
Jan

**Comment by RaspberryConnect** [comment]
Hi Jan

Thanks for the update. I have completed the Bookworm version for PiOS . It has not been tested on Diet Pi yet. I have tested it on Ubuntu and that just needed iw installed but have not updated the installer for that.
I plan on checking out various distributions making it compatible with any that use Network Manager, but that's for the new year.
The Bookworm version is on my website for now, it was only release last week.  www.raspberryconnect.com at the bottom of the home page.
I will look to make any mods for Ubuntu/ Diet Pi and other that I try in Jan as well as making further developments through next year.

Regards
Graeme
