### ISSUE TITLE
Hotspot not broadcasting

### ISSUE THREAD

**Issue by iamthebammbamm** [RaspberryConnect/AutoHotspot-Installer#2]
Using Option 2 with a Pi Zero W. Tried commenting out /etc/dhcpd.conf and also outright deleting it per the other closed issue. Still not broadcasting. Any suggestions?

**Comment by RaspberryConnect** [comment]
Hi,  The closed issue refers to option 3 which is different and any custom changes in dhcpcd.conf that where already in place in addition to the defaults and to what the script has setup.  You will need to add the dhcpcd.conf options back in otherwise this will mean the connection to your router is always made and the access point, though running, is not accessible. You can just run option 2 again to put it back.

I presume you are not seeing the RPiHotspot wifi being broadcast to other devices?  
Which version of Raspbian/PIOS are you using? 
Are there any custom changes that have been made to /etc/dhcpcd.conf /etc/dnsmasq.conf etc/hostapd/hostapd.conf
How are you triggering the access point mode. are you out of range of your router or using option 6?

This type of thing is usually because hostapd has failed due to config issues like the password being less than 8 characters.
If you can access your Pizero via a display then sudo systemctl status hostapd will show any errors while in access point mode.
also try running the script manually and see what responses it gives. sudo /usr/bin/autohotspot
you can put in access point mode by editing your routers ssid in  /etc/wpa_supplicant/wpa_supplicant.conf 
and adding "off" to the end of your routers ssid ie ssid="my_ssidoff"  then run the autohotspot script again.

Any additional info on you setup  will be useful.

**Comment by iamthebammbamm** [comment]
Ok, I tried everything above in multiple combinations, commenting stuff, uncommenting stuff, installing, uninstalling. No idea what finally did it, but I got it working. And since it's linux, as long as I never touch it again, it'll work beautifully forever. Thanks!
