### ISSUE TITLE
Feature request : Add a webpage for configuration

### ISSUE THREAD

**Issue by moustic999** [RaspberryConnect/AutoHotspot-Installer#6]
That would be very good to have a Http web server service with webpage which would allow to see list of available ssid and possibility to configure ssid/password .

That could be a very good entry point for a lot of IOT project, that requires easy configuration.

I have some python knowledge, I can have a try at this task.

**Comment by RaspberryConnect** [comment]
Hi, 
Thanks for the request. I have had a few requests for a web interface in the past but didn't put time to develop that.
I have recently decided to do some updates and make the script more useful in general. So I am currently working on new features and capabilities for the access point of which a web interface for configuration and controls will be part of.
So that will be on it's way once I have developed some other features that will use it.
