### ISSUE TITLE
Is there a way to specify one of the 8 options in the script from terminal 

### ISSUE THREAD

**Issue by tennisparty** [RaspberryConnect/AutoHotspot-Installer#8]
I would like to trigger option 6 automatically when running the script 

I have tried 
`sudo ./autohotspot-setup.sh -6`

I am still presented with 8 options and have to type in 6 and enter manually. Is there a way to choose one of the options without entering it manually when the script is run? I could modify the script but wondered if there was a way natively?

**Comment by RaspberryConnect** [comment]
Hi, The script is just a setup menu so wasn't designed for arguments. Option 6 was more for testing it all works rather than a feature as the autohotspot scripts weren't originally intended for the Access Point to be available near your router. That's how I intended to use it but as there is a wider range of uses I am rewriting the script and will be adding more features and arguments in the near future.

**Comment by tennisparty** [comment]
Amazing that's good to know
